language: python
sudo: required
dist: trusty
python:
 - "2.7"

# https://stackoverflow.com/a/35029430/6605826

virtualenv:
  system_site_packages: true

install:
 - sudo apt-get update
 - sudo apt-get -y install python-pyqt4
 - pip install -r requirements.txt
script:
 - ./test.sh
