language: python
sudo: required
dist: bionic
python:
 - "2.7"
 - "3.6"
 - "3.7"

# https://stackoverflow.com/a/35029430/6605826
# system_site_packages limits py versions https://travis-ci.community/t/python-3-6-and-3-7-with-system-site-packages-enabled-fails-to-activate-on-xenial/1697

virtualenv:
  system_site_packages: true

# apt-get commands depend on py version: https://stackoverflow.com/a/20621143/6605826
install:
 - sudo apt-get update
 - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then sudo apt-get -y install python-qt4; fi
 - if [[ $TRAVIS_PYTHON_VERSION > 3 ]]; then sudo apt-get -y install python3-qt5; fi
 - pip install -r requirements.txt
 - pip install codecov coverage

before_script:
 # From pyqtgraph's .travis.yml: https://github.com/pyqtgraph/pyqtgraph/blob/develop/.travis.yml
 # We need to create a (fake) display on Travis, let's use a funny resolution
 - export DISPLAY=:99.0
 - "sh -e /etc/init.d/xvfb start"
 - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
 - export PGMPL_TEST_VERBOSE=1

script:
 - coverage run -m unittest discover --pattern=*.py -s tests

after_success:
 - codecov
