language: python
sudo: required
dist: trusty
python:
 - "2.7"

# https://stackoverflow.com/a/35029430/6605826

virtualenv:
  system_site_packages: true

install:
 - pip install -r requirements.txt
 - pip install codecov coverage

before_script:
 # From pyqtgraph's .travis.yml: https://github.com/pyqtgraph/pyqtgraph/blob/develop/.travis.yml
 # We need to create a (fake) display on Travis, let's use a funny resolution
 - export DISPLAY=:99.0
 - "sh -e /etc/init.d/xvfb start"
 - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
 - export PGMPL_TEST_VERBOSE=1

script:
 - coverage run -m unittest discover --pattern=*.py -s tests

after_success:
 - codecov
