language: python
sudo: required
jobs:
  include:
    - name: "python 3.6 qt5 bionic pgmpl"
      dist: bionic
      python: 3.6
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install python3-pyqt5
      services:
       - xvfb
    - name: "python 3.9 qt5 bionic pgmpl"
      dist: bionic
      python: 3.9
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install python3-pyqt5
      services:
       - xvfb

# https://stackoverflow.com/a/35029430/6605826
# system_site_packages limits py versions https://travis-ci.community/t/python-3-6-and-3-7-with-system-site-packages-enabled-fails-to-activate-on-xenial/1697
virtualenv:
  system_site_packages: true

# apt-get commands depend on py version: https://stackoverflow.com/a/20621143/6605826
install:
# - sudo apt-get update
# - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then sudo apt-get -y install python-qt4; fi
# - if [[ $TRAVIS_PYTHON_VERSION > 3 ]]; then sudo apt-get -y install python3-pyqt5; fi
 - pip install -r requirements.txt
 - pip install codecov coverage

script:
 - coverage run -m unittest discover --pattern=*.py -s tests

after_success:
 - codecov
